dspiniscnspin=true
DSPinUseGui=false
HideCacheDsPinCheck=false
idspiniscnspin=true
iDSPinUseGui=false
iHideCacheDsPinCheck=false
gcdspiniscnspin=false
gcDSPinUseGui=true
gcHideCacheDsPinCheck=false
odspiniscnspin=true
oDSPinUseGui=false
oHideCacheDsPinCheck=false
